### ISSUE TITLE
Support for UWP browsers

### ISSUE THREAD

**Issue by dfibuch** [MintPlayer/MintPlayer.BrowserDialog#5]
This isn't really an issue, more of a suggestion with some code to help. I have tested this package with various browsers and spotted that it wasn't picking up my DuckDuckGo browser which installs as a Windows App (UWP). I looked into it and found a way to do it, which is fairly simple and works with .NET 7.0. 

Here is the info:

First, in your `.csproj` you need to specifically target a Windows OS (in my case I did Windows 10, doesn't look like it works with previous versions) by setting your TargetFramework:

`<TargetFramework>net7.0-windows10.0.22621.0</TargetFramework>`

Then for the code you use `PackageManager` from the `Windows.Management.Deployment` namespace. In my example I am specifically looking for the DDG browser but Im sure there are smarter ways to go about finding others (like search for `browser` or something):

```c#
        PackageManager packageManager = new PackageManager();

        IEnumerable<Windows.ApplicationModel.Package> packages = packageManager.FindPackagesForUser("");
         
        foreach (var package in packages.Where(p => p.Id.FullName.Contains("duck", StringComparison.OrdinalIgnoreCase)))
        {
            Console.WriteLine(package.Id.FullName);
        }
```

Just a suggestion, see what you guys think :-)

**Comment by PieterjanDeClippel** [comment]
Thanks for reporting this.

Doing this would tight this library to the uwp platform. Thanks to [this pull request](https://github.com/MintPlayer/MintPlayer.BrowserDialog/pull/1) this library started targetting .NET Standard, which is compatible with all SDK's.

Even though AFAIK only Windows supports retrieving installed webbrowsers, and there's only .NET Core across all platforms left, I would prefer to keep targetting .NET Standard for now.

We can add another library specifically targetting `net7.0-windows` which consumes the existing library and unions the results of both. That is if the registry is available in UWP?

**Comment by dfibuch** [comment]
Good point, I was only thinking about Windows as it's the problem I needed to solve. There are various ways of solving this but it's up to you guys to decide if it needs solving :-) Also, I couldn't find a reliable way of finding UWP web browsers except for searching their names for the usual terms like "browser, internet, search" which isn't great, but it's better than nothing.

I'll close the issue, thanks for looking at it and responding.

**Comment by PieterjanDeClippel** [comment]
Hi,

I implemented the code. Note that you seem to have to target a specific windows version in your application for it to work.
Thanks for the idea 🥳🥳🥳

**Comment by dfibuch** [comment]
Oh sweet, nice one! I know my implementation was very limited, I didn't have the time for getting a fully working solution. Just enough to play around with it to know what needs to be done. Glad it helped and improved your package :-)
